# Generated by Django 3.0 on 2020-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idsp',
            fields=[
                ('spid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'idsp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liuxiangpinzhong',
            fields=[
               # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liuxiangid', models.IntegerField(db_column='LiuXiangId')),
                ('spbh_c', models.CharField(db_column='Spbh_C', max_length=15)),
                ('shifoushengxiao', models.IntegerField(db_column='ShiFouShengXiao')),
            ],
            options={
                'db_table': 'LiuXiangPinZHong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('spbh', models.CharField(max_length=500)),
                ('spmch', models.CharField(max_length=500)),
                ('shpgg', models.CharField(max_length=500)),
                ('shengccj', models.CharField(max_length=500)),
                ('shl', models.CharField(max_length=500)),
                ('dwmch', models.CharField(max_length=500)),
                ('sxrq', models.CharField(max_length=500)),
                ('pihao2', models.CharField(max_length=500)),
                ('rkrq', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('dw', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spbh', models.CharField(max_length=500)),
                ('spmch', models.CharField(max_length=500)),
                ('shpgg', models.CharField(max_length=500)),
                ('shengccj', models.CharField(max_length=500)),
                ('shl2', models.CharField(max_length=500)),
                ('rq', models.CharField(max_length=500)),
                ('sxrq', models.CharField(max_length=500)),
                ('pihao2', models.CharField(max_length=500)),
                ('hshj', models.CharField(max_length=500)),
                ('hsje', models.CharField(max_length=500)),
                ('dwmch', models.CharField(max_length=500)),
                ('dw', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spbh', models.CharField(max_length=500)),
                ('spmch', models.CharField(max_length=500)),
                ('shpgg', models.CharField(max_length=500)),
                ('pihao2', models.CharField(max_length=500)),
                ('dwmch', models.CharField(max_length=500)),
                ('rq', models.CharField(max_length=500)),
                ('shl', models.CharField(max_length=500)),
                ('hshj', models.CharField(max_length=500)),
                ('hsje', models.CharField(max_length=500)),
                ('sxrq', models.CharField(max_length=500)),
                ('kaipy', models.CharField(max_length=500)),
                ('shengccj', models.CharField(max_length=500)),
                ('dw', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('password', models.CharField(db_column='PassWord', max_length=50)),
                ('type', models.CharField(db_column='Type', max_length=50)),
                ('isok', models.BooleanField(db_column='IsOK')),
                ('liuxiangid', models.IntegerField(blank=True, db_column='LiuXiangId', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
